name: CI/CD Pipeline

on:
  push:
    branches: ['main']

jobs:
  setup-node:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        shell: cmd

      - name: Save Node modules
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: |
            node_modules
            package-lock.json

      

  build-and-push-image:
    runs-on: windows-latest
    needs: setup-node
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Node modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules
      
      - name: Add server certificate to Node.js trust store
        run: echo ${{ secrets.SERVER_CERT }} > /usr/local/share/ca-certificates/server.crt && update-ca-certificates
        env:
          NODE_EXTRA_CA_CERTS: /usr/local/share/ca-certificates/server.crt
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Add server certificate to Docker trust store
        run: |
          mkdir -p /etc/docker/certs.d/yourserver:port
          echo ${{ secrets.SERVER_CERT }} > /etc/docker/certs.d/yourserver:port/ca.crt

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
