name: CI/CD Pipeline

on:
  push:
    branches: ['main']

jobs:
  setup-node:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
        shell: cmd

      - name: Save Node modules
        uses: actions/upload-artifact@v3
        with:
          name: node-modules
          path: |
            node_modules
            package-lock.json
  
  sonarqube-analysis:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Node modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules

      - name: Install SonarQube Scanner
        run: npm install sonarqube-scanner --save-dev

      - name: SonarQube analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          npx sonarqube-scanner \
            -Dsonar.projectKey=rsademo \
            -Dsonar.sources=. \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: setup-node
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore Node modules
        uses: actions/download-artifact@v3
        with:
          name: node-modules

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-world:latest
